def remote = Remote.create();
remote.connect("virtualhost", 22, "user", "password");
remote.execute("mkdir forSendDirtest");
remote.execute("touch forSendDirtest/groovy.pacifista.txt");
def templateparameter = "replaced value";
def username = env.get("USER");
def template = Template.create("testTemplate.vm");
template.put("parameter", templateparameter);
template.put("username", username);
template.put("lang", "groovy");
def config = template.toValue();
remote.send(config, "forSendDirtest", "groovyConfig");
remote.close();
console.log("groovy complete");