var remote = Remote.create();
remote.connect("virtualhost", 22, "user", "password");
remote.execute("mkdir forSendDirtest");
remote.execute("touch forSendDirtest/javaScript.pacifista.txt");
var templateparameter = "replaced value";
var username = runtime.getEnv("USER");
var template = Template.create("testTemplate.vm");
template.put("parameter", templateparameter);
template.put("username", username);
template.put("lang", "javaScript");
var config = template.toValue();
remote.send(config, "forSendDirtest", "jsConfig");
var tester = Tester.create(remote);
tester.assertFile("/etc/hosts", "rw-r--r--", "root");
tester.portOpen(22);
remote.close();
runtime.call("sampleScripts/otherScript.js");
console.log("javaScript complete");
